import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Semantic tokens (preferred) */
        surface: {
          canvas: "var(--surface-canvas)",
          raised: "var(--surface-raised)",
          sunken: "var(--surface-sunken)",
          inverse: "var(--surface-inverse)",
          muted: "var(--surface-muted)",
        },
        ink: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          quaternary: "var(--text-quaternary)",
          inverse: "var(--text-inverse)",
          accent: "var(--text-accent)",
        },
        line: {
          subtle: "var(--border-subtle)",
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
          accent: "var(--border-accent)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          deep: "var(--accent-deep)",
          tint: "var(--accent-tint)",
          wash: "var(--accent-wash)",
        },
        stone: {
          50:  "var(--stone-50)",
          100: "var(--stone-100)",
          200: "var(--stone-200)",
          300: "var(--stone-300)",
          400: "var(--stone-400)",
          500: "var(--stone-500)",
          600: "var(--stone-600)",
          700: "var(--stone-700)",
          800: "var(--stone-800)",
          900: "var(--stone-900)",
          950: "var(--stone-950)",
        },
        status: {
          success:       "var(--success)",
          "success-tint":   "var(--success-tint)",
          "success-border": "var(--success-border)",
          "success-text":   "var(--success-text)",
          warning:       "var(--warning)",
          "warning-tint":   "var(--warning-tint)",
          "warning-border": "var(--warning-border)",
          "warning-text":   "var(--warning-text)",
          danger:        "var(--danger)",
          "danger-tint":    "var(--danger-tint)",
          "danger-border":  "var(--danger-border)",
          "danger-text":    "var(--danger-text)",
          info:          "var(--info)",
          "info-tint":      "var(--info-tint)",
          "info-border":    "var(--info-border)",
          "info-text":      "var(--info-text)",
        },

        /* TAG legacy — preserved */
        tag: {
          orange: {
            DEFAULT: "#f97316",
            hover: "#ea6c0a",
            deep: "#c2530a",
            light: "#fed7aa",
            pale: "#fff7ed",
            mid: "#fb923c",
          },
          amber: { DEFAULT: "#fbbf24", light: "#fef3c7" },
          heading: "#1a1714",
          label: "#44403c",
          body: "#78716c",
          bg: {
            DEFAULT: "#ffffff",
            warm: "#fafaf8",
            orange: "#fef9f6",
          },
          dark: { DEFAULT: "#1c1917", deep: "#0c0a09" },
          border: {
            DEFAULT: "#ece8e3",
            orange: "#fed7aa",
            soft: "#ffedd5",
            dashed: "#c2530a",
            amber: "#fef3c7",
          },
          success: {
            DEFAULT: "#16a34a",
            text: "#15803d",
            bg: "rgba(22,163,74,0.15)",
            border: "rgba(22,163,74,0.3)",
          },
          warning: {
            DEFAULT: "#d97706",
            bg: "rgba(217,119,6,0.15)",
            border: "rgba(217,119,6,0.3)",
          },
          danger: {
            DEFAULT: "#ef4444",
            text: "#dc2626",
            bg: "rgba(239,68,68,0.15)",
            border: "rgba(239,68,68,0.3)",
          },
        },
      },
      fontFamily: {
        sans: ["var(--font-sohne)", "SF Pro Display", "-apple-system", "sans-serif"],
        display: ["var(--font-sohne)", "SF Pro Display", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        "display-hero":    ["3.50rem", { lineHeight: "1.03", letterSpacing: "-0.03em", fontWeight: "300" }],
        "display-large":   ["2.50rem", { lineHeight: "1.10", letterSpacing: "-0.025em", fontWeight: "300" }],
        "section-heading": ["1.75rem", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "300" }],
        "sub-heading-lg":  ["1.375rem",{ lineHeight: "1.20", letterSpacing: "-0.015em", fontWeight: "300" }],
        "sub-heading":     ["1.125rem",{ lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg":         ["1.0625rem",{ lineHeight: "1.55", fontWeight: "300" }],
        eyebrow:           ["0.6875rem",{ lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "500" }],
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
        micro: "2px",
        standard: "4px",
        comfortable: "5px",
        relaxed: "6px",
        large: "8px",
      },
      boxShadow: {
        "e1": "var(--elevation-1)",
        "e2": "var(--elevation-2)",
        "e3": "var(--elevation-3)",
        "e4": "var(--elevation-4)",
        "focus": "var(--focus-ring)",
        "focus-danger": "var(--focus-ring-danger)",
        /* TAG legacy shadows kept */
        "tag-ambient": "rgba(23,23,23,0.06) 0px 3px 6px",
        "tag-standard": "var(--elevation-2)",
        "tag-elevated": "var(--elevation-3)",
        "tag-elevated-hover": "var(--elevation-3)",
        "tag-modal": "var(--elevation-4)",
        "tag-focus": "var(--focus-ring)",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.22, 1, 0.36, 1)",
        "in-out-cubic": "cubic-bezier(0.65, 0, 0.35, 1)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "200ms",
        slow: "320ms",
      },
      fontFeatureSettings: {
        ss01: '"ss01"',
        tnum: '"tnum"',
      },
    },
  },
  plugins: [],
};

export default config;
